const state={lang:'vi',role:'admin',activeModule:'transactions',docTab:'confirmation',editing:null,
seller:{nameVi:'CÔNG TY TNHH HADAY VIỆT NAM',nameZh:'海天越南有限公司',tax:'0318185296',addressVi:'Số 168, Đường Hà Huy Tập, Phường Tân Hưng, Thành phố Hồ Chí Minh, Việt Nam',addressZh:'越南胡志明市新兴坊何辉集路168号',representative:'PEI, YINGBIN / 裴迎宾',position:'TỔNG GIÁM ĐỐC / 总经理',phone:'+84-2854166016',email:'yingbin.pei@haday.com.vn'},
customers:[{code:'2141010050',nameVi:'CÔNG TY TNHH THƯƠNG MẠI XUẤT NHẬP KHẨU TUẤN PHƯƠNG',nameZh:'俊芳贸易进出口有限公司',tax:'0108272471',addressVi:'Số 77 Phố Hàm Tử Quan, Phường Phúc Tân, Quận Hoàn Kiếm, Thành phố Hà Nội, Việt Nam',addressZh:'越南河内市还剑郡福新坊咸子关街77号',representative:'TRẦN MINH HOÀNG / 陈明黄',position:'TỔNG GIÁM ĐỐC / 总经理',phone:'0939368123',email:'contact@tuanphuong.vn'},{code:'2141020110',nameVi:'CÔNG TY TNHH THƯƠNG MẠI HOÀNG THIÊN PHÁT',nameZh:'越南黄天发贸易有限公司',tax:'0316353410',addressVi:'387 Phan Văn Trị, Phường Bình Lợi Trung, TP Hồ Chí Minh, Việt Nam',addressZh:'越南胡志明市平盛郡潘文治路387号',representative:'TRẦN MINH HOÀNG / 陈明黄',position:'TỔNG GIÁM ĐỐC / 总经理',phone:'0939368123',email:'tranminhhoang@thp.vn'}],
products:[{sku:'89107250005',nameVi:'HADAY NƯỚC TƯƠNG CAO CẤP 750ML*6',nameZh:'海天高级酱油（750毫升）',unit:'Chai',price:22660,packing:'750ML × 6',barcode:'89107250005',active:true},{sku:'89107263005',nameVi:'HADAY DẦU HÀO CAO CẤP 700G',nameZh:'海天高级蚝油（700克）',unit:'Hũ',price:34800,packing:'700G × 12',barcode:'89107263005',active:true},{sku:'89107210905',nameVi:'HADAY NƯỚC TƯƠNG NHẠT 1.9L',nameZh:'海天生抽酱油（1.9升）',unit:'Chai',price:25100,packing:'1.9L × 6',barcode:'89107210905',active:true},{sku:'89107264005',nameVi:'HADAY XỐT HÀO 2.2KG',nameZh:'海天蚝油（2.2公斤）',unit:'Hũ',price:98500,packing:'2.2KG × 6',barcode:'89107264005',active:true},{sku:'89107270005',nameVi:'HADAY GIẤM GẠO 500ML',nameZh:'海天米醋（500毫升）',unit:'Chai',price:18300,packing:'500ML × 12',barcode:'89107270005',active:true}],
payments:[{code:'DAP',vi:'DAP - Giao tại nơi đến',zh:'DAP - 目的地交货'},{code:'T/T',vi:'T/T - Chuyển khoản',zh:'T/T - 电汇'}],
selectedCustomer:0,items:[{productIndex:0,qty:100},{productIndex:1,qty:50}],discount:0,extraFee:0,vatRate:8};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], money=n=>Math.round(Number(n||0)).toLocaleString('vi-VN');
function customer(){return state.customers[state.selectedCustomer]||state.customers[0]}
function sellerHtml(s=state.seller){return `<p><b>${s.nameVi}</b></p><p><b>${s.nameZh}</b></p><p>Mã số thuế / 税号: ${s.tax}</p><p>Địa chỉ / 地址: ${s.addressVi}<br/>${s.addressZh}</p><p>Người đại diện / 代表人: ${s.representative}</p><p>Chức vụ / 职务: ${s.position}</p><p>Điện thoại / 电话: ${s.phone}</p><p>Email / 邮箱: ${s.email}</p>`}
function buyerHtml(c=customer()){return `<p><b>${c.nameVi}</b></p><p><b>${c.nameZh}</b></p><p>Mã khách hàng / 客户编码: ${c.code}</p><p>Mã số thuế / 税号: ${c.tax}</p><p>Địa chỉ / 地址: ${c.addressVi}<br/>${c.addressZh}</p><p>Người đại diện / 代表人: ${c.representative}</p><p>Chức vụ / 职务: ${c.position}</p><p>Điện thoại / 电话: ${c.phone}</p><p>Email / 邮箱: ${c.email}</p>`}
function init(){ $('#orderDate').value=new Date().toISOString().slice(0,10); bind(); renderAll(); }
function bind(){
 $$('#mainNav .nav-item').forEach(b=>b.onclick=()=>switchModule(b.dataset.module)); $$('.subtab').forEach(b=>b.onclick=()=>switchDocTab(b.dataset.docTab));
 $('#roleSelect').onchange=e=>{state.role=e.target.value;applyRole()}; $('#languageSelect').onchange=e=>state.lang=e.target.value;
 $('#customerPicker').onchange=e=>{state.selectedCustomer=+e.target.value;renderParties()}; $('#addProductRow').onclick=()=>{state.items.push({productIndex:'',qty:1});renderTransactionItems()};
 $('#discount').oninput=e=>{state.discount=+e.target.value;renderTotals()}; $('#extraFee').oninput=e=>{state.extraFee=+e.target.value;renderTotals()}; $('#vatRate').oninput=e=>{state.vatRate=+e.target.value;renderTotals()};
 $('#orderNo').oninput=syncAppendix; $('#orderDate').oninput=syncAppendix; $('#signingPlace').oninput=syncAppendix; $('#printBtn').onclick=()=>window.print(); $('#exportBtn').onclick=exportWorkbook; $('#excelInput').onchange=importWorkbook;
 $('#productSearch').oninput=renderProductData; $('#addProduct').onclick=()=>openEditor('product'); $('#addCustomer').onclick=()=>openEditor('customer'); $('#addPayment').onclick=()=>openEditor('payment'); $('#productExport').onclick=exportProducts; $('#productImport').onchange=importProducts;
 $('#sellerForm').onsubmit=e=>e.preventDefault(); $('#editForm').onsubmit=saveEditor;
}
function switchModule(id){state.activeModule=id;$$('.module').forEach(x=>x.classList.remove('active'));$('#module-'+id).classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.module===id));const titles={transactions:'Giao dịch',products:'Dữ liệu sản phẩm',customers:'Dữ liệu khách hàng',seller:'Thông tin Bên bán',payment:'Điều khoản thanh toán',guide:'Hướng dẫn sử dụng'};$('#pageTitle').textContent=titles[id]||id}
function switchDocTab(id){state.docTab=id;$$('.subtab').forEach(x=>x.classList.toggle('active',x.dataset.docTab===id));$$('.doc-tab').forEach(x=>x.classList.remove('active'));$('#doc-'+id).classList.add('active');syncAppendix()}
function renderAll(){renderPickers();renderParties();renderTransactionItems();renderProductData();renderCustomerData();renderSellerForm();renderPayments();renderTerms();applyRole();syncAppendix()}
function renderPickers(){ $('#customerPicker').innerHTML=state.customers.map((c,i)=>`<option value="${i}" ${i===state.selectedCustomer?'selected':''}>${c.nameVi}</option>`).join(''); $('#paymentPicker').innerHTML=state.payments.map(p=>`<option value="${p.code}">${p.code} — ${p.vi}</option>`).join('') }
function renderParties(){ $('#sellerSummary').innerHTML=sellerHtml();$('#customerSummary').innerHTML=buyerHtml();syncAppendix() }
function renderTransactionItems(){const body=$('#transactionItems');body.innerHTML=state.items.map((it,i)=>{const p=state.products[it.productIndex];return `<tr><td>${i+1}</td><td><select data-pick="${i}"><option value="">— Chọn sản phẩm —</option>${state.products.filter(x=>x.active).map((x,j)=>`<option value="${j}" ${j===it.productIndex?'selected':''}>${x.nameVi}</option>`).join('')}</select></td><td>${p?.sku||''}</td><td>${p?.nameZh||''}</td><td>${p?.unit||''}</td><td><input type="number" min="0" value="${it.qty||0}" data-qty="${i}" /></td><td>${p?money(p.price):''}</td><td>${p?money(p.price*(it.qty||0)):''}</td><td class="no-print"><button class="row-delete" data-remove="${i}">🗑</button></td></tr>`}).join('');$$('[data-pick]').forEach(s=>s.onchange=e=>{state.items[+e.target.dataset.pick].productIndex=e.target.value===''?'':+e.target.value;renderTransactionItems()});$$('[data-qty]').forEach(x=>x.oninput=e=>{state.items[+e.target.dataset.qty].qty=+e.target.value;renderTotals();syncAppendix()});$$('[data-remove]').forEach(b=>b.onclick=()=>{state.items.splice(+b.dataset.remove,1);renderTransactionItems()});renderTotals();syncAppendix()}
function totals(){const goods=state.items.reduce((s,it)=>{const p=state.products[it.productIndex];return s+(p?p.price*(it.qty||0):0)},0),before=goods-state.discount+state.extraFee,vat=Math.round(before*state.vatRate/100),grand=before+vat;return{goods,before,vat,grand}}
function renderTotals(){const t=totals();$('#goodsTotal').value=money(t.goods);$('#beforeTax').value=money(t.before);$('#vatAmount').value=money(t.vat);$('#grandTotal').value=money(t.grand);$('#amountWords').textContent=numberToVietnamese(t.grand)+' đồng chẵn.';syncAppendix()}
function syncAppendix(){const t=totals(),no=$('#orderNo')?.value||'';$('#appendixNo').textContent=no;$('#appendixOrderNo').textContent=no;$('#appendixDate').textContent=$('#orderDate')?.value||'';$('#appendixPlace').textContent=$('#signingPlace')?.value||'';$('#appendixSeller').innerHTML=sellerHtml();$('#appendixBuyer').innerHTML=buyerHtml();$('#contractRef').textContent=no;$('#contractRefZh').textContent=no;const rows=[['(1)','Tổng giá trị hàng hóa trước chiết khấu / 商品金额小计（折扣前）',t.goods],['(2)','Chiết khấu thương mại / 商业折扣',state.discount],['(3)','Chiết khấu thanh toán / 付款折扣',0],['(4)','Tổng tiền hàng sau chiết khấu / 折扣后金额',t.goods-state.discount],['(5)','Chiết khấu đặc biệt / Hỗ trợ bán hàng / 特别折扣',0],['(6)','Thành tiền sau các loại chiết khấu / 商品金额小计（总金额）',t.goods-state.discount],['(7)','Chi phí chiết khấu / 折扣费用',state.discount],['(8)','Các khoản phụ phí khác / 其他附加费用',state.extraFee],['(9)','Không chịu thuế tổng / 不含税总金额',t.before],['(10)',`Thuế GTGT (${state.vatRate}%) / 增值税`,t.vat],['(11)','Tổng số tiền thanh toán / 含税总金额',t.grand]];$('#appendixTotals').innerHTML=rows.map((r,i)=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td class="${i===10?'grand-value':''}">${money(r[2])}</td></tr>`).join('');$('#appendixWords').textContent=numberToVietnamese(t.grand)+' đồng chẵn.'}
function renderTerms(){const pairs=[['Nếu người nhận hàng là bên thứ ba không phải Bên Mua, Bên Mua vẫn phải thanh toán trực tiếp cho Bên Bán đầy đủ số tiền theo Bản xác nhận này.','若收货人为买方以外的第三方，买方仍应按本确认书约定向卖方支付全部款项。'],['Bản xác nhận này là một phần không thể tách rời của hợp đồng được ký giữa Bên Mua và Bên Bán.','本确认书是买卖双方合同不可分割的一部分。'],['Bản quét, bản sao và chữ ký điện tử có giá trị pháp lý tương đương bản gốc.','扫描件、复印件及电子签名与原件具有同等法律效力。'],['Sau khi hàng được vận chuyển tới địa điểm chỉ định, người nhận hàng tiến hành ký nhận.','货物运至指定地点后由指定收货人签收。']];$('#termsText').innerHTML=pairs.map((p,i)=>`<p>(${i+1}) ${p[0]}</p><p>(${i+1}) ${p[1]}</p>`).join('')}
function renderProductData(){const q=($('#productSearch')?.value||'').toLowerCase();$('#productDataBody').innerHTML=state.products.map((p,i)=>({...p,i})).filter(p=>!q||[p.sku,p.nameVi,p.nameZh].join(' ').toLowerCase().includes(q)).map(p=>`<tr><td>${p.i+1}</td><td>${p.sku}</td><td>${p.nameVi}</td><td>${p.nameZh}</td><td>${p.unit}</td><td>${money(p.price)}</td><td>${p.packing}</td><td>${p.barcode}</td><td>${p.active?'Đang dùng':'Ngừng dùng'}</td><td><button class="edit-button edit-only" data-edit-product="${p.i}">✎</button><button class="delete-button edit-only" data-delete-product="${p.i}">🗑</button></td></tr>`).join('');$$('[data-edit-product]').forEach(b=>b.onclick=()=>openEditor('product',+b.dataset.editProduct));$$('[data-delete-product]').forEach(b=>b.onclick=()=>{if(confirm('Xóa sản phẩm này?')){state.products.splice(+b.dataset.deleteProduct,1);renderAll()}});applyRole()}
function renderCustomerData(){$('#customerDataBody').innerHTML=state.customers.map((c,i)=>`<tr><td>${i+1}</td><td>${c.code}</td><td>${c.nameVi}</td><td>${c.nameZh}</td><td>${c.tax}</td><td>${c.addressVi}</td><td>${c.representative}</td><td>${c.phone}</td><td><button class="edit-button edit-only" data-edit-customer="${i}">✎</button><button class="delete-button edit-only" data-delete-customer="${i}">🗑</button></td></tr>`).join('');$$('[data-edit-customer]').forEach(b=>b.onclick=()=>openEditor('customer',+b.dataset.editCustomer));$$('[data-delete-customer]').forEach(b=>b.onclick=()=>{if(confirm('Xóa khách hàng này?')){state.customers.splice(+b.dataset.deleteCustomer,1);state.selectedCustomer=0;renderAll()}});applyRole()}
function renderSellerForm(){const labels={nameVi:'Tên công ty (Việt)',nameZh:'Tên công ty (Trung)',tax:'Mã số thuế',addressVi:'Địa chỉ (Việt)',addressZh:'Địa chỉ (Trung)',representative:'Người đại diện',position:'Chức vụ',phone:'Điện thoại',email:'Email'};$('#sellerForm').innerHTML=Object.entries(labels).map(([k,l])=>`<label>${l}<input name="${k}" value="${state.seller[k]||''}" ${state.role==='viewer'?'disabled':''}></label>`).join('')+`<div><button class="btn primary edit-only" type="button" id="saveSeller">Lưu thông tin</button></div>`;$('#saveSeller')?.addEventListener('click',()=>{$$('#sellerForm input').forEach(x=>state.seller[x.name]=x.value);renderParties();alert('Đã lưu thông tin Bên bán')});applyRole()}
function renderPayments(){$('#paymentList').innerHTML=state.payments.map((p,i)=>`<div class="payment-card"><div><b>${p.code}</b><div>${p.vi}</div><div>${p.zh}</div></div><div><button class="edit-button edit-only" data-edit-payment="${i}">✎</button><button class="delete-button edit-only" data-delete-payment="${i}">🗑</button></div></div>`).join('');$$('[data-edit-payment]').forEach(b=>b.onclick=()=>openEditor('payment',+b.dataset.editPayment));$$('[data-delete-payment]').forEach(b=>b.onclick=()=>{state.payments.splice(+b.dataset.deletePayment,1);renderAll()});applyRole()}
function applyRole(){const editable=state.role==='admin',sales=state.role==='sales';$$('.edit-only').forEach(x=>x.classList.toggle('hidden',!editable));$('#roleHint').textContent=editable?'Được chỉnh sửa dữ liệu gốc':sales?'Được lập giao dịch, không sửa dữ liệu gốc':'Chỉ được xem';$$('#module-transactions input,#module-transactions select,#module-transactions button').forEach(x=>{if(x.id==='printBtn')return;x.disabled=state.role==='viewer'});renderSellerFormSafe()}
function renderSellerFormSafe(){const f=$('#sellerForm');if(!f)return;f.querySelectorAll('input').forEach(x=>x.disabled=state.role!=='admin')}
function openEditor(type,index=null){state.editing={type,index};const schemas={product:[['sku','SKU'],['nameVi','Tên tiếng Việt'],['nameZh','Tên tiếng Trung'],['unit','Đơn vị'],['price','Đơn giá VND','number'],['packing','Quy cách'],['barcode','Barcode']],customer:[['code','Mã khách hàng'],['nameVi','Tên Việt'],['nameZh','Tên Trung'],['tax','Mã số thuế'],['addressVi','Địa chỉ Việt'],['addressZh','Địa chỉ Trung'],['representative','Người đại diện'],['position','Chức vụ'],['phone','Điện thoại'],['email','Email']],payment:[['code','Mã điều khoản'],['vi','Tên tiếng Việt'],['zh','Tên tiếng Trung']]};const obj=index===null?{}:state[type==='product'?'products':type==='customer'?'customers':'payments'][index];$('#editTitle').textContent=index===null?'Thêm mới':'Chỉnh sửa';$('#editFields').innerHTML=schemas[type].map(([k,l,tp])=>`<label>${l}<input name="${k}" type="${tp||'text'}" value="${obj[k]??''}"></label>`).join('');$('#editDialog').showModal()}
function saveEditor(e){e.preventDefault();const fd=Object.fromEntries(new FormData($('#editForm')).entries()),{type,index}=state.editing;if(type==='product'){fd.price=+fd.price;fd.active=true}const arr=state[type==='product'?'products':type==='customer'?'customers':'payments'];if(index===null)arr.push(fd);else arr[index]=fd;$('#editDialog').close();renderAll()}
function exportWorkbook(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.customers),'Khach_hang');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.products),'San_pham');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.payments),'Dieu_khoan');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.items.map((it,i)=>{const p=state.products[it.productIndex]||{};return{STT:i+1,SKU:p.sku,'Tên sản phẩm':p.nameVi,'Tên Trung':p.nameZh,'Đơn vị':p.unit,'Số lượng':it.qty,'Đơn giá VND':p.price,'Thành tiền VND':p.price*it.qty}})),'Giao_dich');XLSX.writeFile(wb,'haday-deal-confirmation-v5.xlsx')}
function exportProducts(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.products),'San_pham');XLSX.writeFile(wb,'du-lieu-san-pham.xlsx')}
function importWorkbook(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=x=>{const wb=XLSX.read(x.target.result,{type:'array'});const names=wb.SheetNames;const pName=names.find(n=>/产品订单|san.?pham|product/i.test(n));const cName=names.find(n=>/客户基础数据|khach.?hang|customer/i.test(n));if(pName){const a=XLSX.utils.sheet_to_json(wb.Sheets[pName],{defval:''});const parsed=a.map(row=>({sku:String(row['物料编码']||row['SKU']||row['Mã hàng / SKU']||''),nameVi:String(row['越南名称']||row['Tên tiếng Việt']||row['Tên sản phẩm']||''),nameZh:String(row['中文名称']||row['小类']||row['Tên tiếng Trung']||''),unit:String(row['单位']||row['Đơn vị']||''),price:Number(row['单价']||row['Đơn giá VND']||0),packing:String(row['Quy cách']||''),barcode:String(row['Barcode']||row['物料编码']||''),active:true})).filter(p=>p.sku||p.nameVi);if(parsed.length)state.products=parsed}if(cName){const a=XLSX.utils.sheet_to_json(wb.Sheets[cName],{defval:''});const parsed=a.map(row=>({code:String(row['客户编码']||row['Mã khách hàng']||''),nameVi:String(row['越南名称']||row['Tên Việt']||''),nameZh:String(row['中文名称']||row['Tên Trung']||''),tax:String(row['税号']||row['Mã số thuế']||''),addressVi:String(row['Địa chỉ']||row['越南地址']||''),addressZh:String(row['中文地址']||''),representative:String(row['Người đại diện']||''),position:String(row['Chức vụ']||''),phone:String(row['Điện thoại']||''),email:String(row['Email']||'')})).filter(c=>c.code||c.nameVi);if(parsed.length)state.customers=parsed}state.selectedCustomer=0;renderAll();alert('Đã nhập dữ liệu Excel')};r.readAsArrayBuffer(f)}
function importProducts(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=x=>{const wb=XLSX.read(x.target.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],a=XLSX.utils.sheet_to_json(ws,{defval:''});const parsed=a.map(row=>({sku:String(row.SKU||row['Mã hàng / SKU']||row['物料编码']||''),nameVi:String(row['Tên tiếng Việt']||row['Tên sản phẩm']||row['越南名称']||''),nameZh:String(row['Tên tiếng Trung']||row['中文名称']||''),unit:String(row['Đơn vị']||row['单位']||''),price:Number(row['Đơn giá VND']||row['单价']||0),packing:String(row['Quy cách']||''),barcode:String(row.Barcode||''),active:true})).filter(p=>p.sku||p.nameVi);if(parsed.length){state.products=parsed;renderAll();alert('Đã nhập dữ liệu sản phẩm')}};r.readAsArrayBuffer(f)}
function numberToVietnamese(num){num=Math.round(num);if(!num)return 'Không';const units=['','nghìn','triệu','tỷ','nghìn tỷ','triệu tỷ'],digits=['không','một','hai','ba','bốn','năm','sáu','bảy','tám','chín'];function three(n,full){let h=Math.floor(n/100),t=Math.floor((n%100)/10),u=n%10,out=[];if(h||full){out.push(digits[h],'trăm')}if(t>1){out.push(digits[t],'mươi');if(u===1)out.push('mốt');else if(u===5)out.push('lăm');else if(u)out.push(digits[u])}else if(t===1){out.push('mười');if(u===5)out.push('lăm');else if(u)out.push(digits[u])}else if(u){if(h||full)out.push('lẻ');out.push(digits[u])}return out.join(' ')}let parts=[],i=0;while(num>0){let g=num%1000;if(g)parts.unshift(three(g,i>0&&g<100)+(units[i]?' '+units[i]:''));num=Math.floor(num/1000);i++}return parts.join(' ').replace(/\s+/g,' ').replace(/^./,c=>c.toUpperCase())}
init();
