import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as XLSX from 'xlsx';
import {BookOpen, Database, Download, FileText, Globe2, LockKeyhole, Package, Plus, Printer, Search, Settings2, Trash2, Upload, UserRound, X} from 'lucide-react';
import './styles.css';

const CUSTOMER_SHEET='客户基础数据';
const PRODUCT_SHEET='产品订单（暂不含工业物料，待更新物料编码及装运信息）';
const PAYMENT_SHEETS=['付款条款参考','付款条款汇总','付款条款筛选'];
const ADDRESS_SHEETS=['客户地址信息汇总','客户地址筛选'];
const SOURCE_SHEETS=[CUSTOMER_SHEET,'三品订单','越南文大写金额计算',...PAYMENT_SHEETS,PRODUCT_SHEET,...ADDRESS_SHEETS];
const LANGS={vi:'Tiếng Việt',zh:'中文（简体）',en:'English'};
const T={
vi:{title:'Xác nhận giao dịch',appendix:'Phụ lục xác nhận giao dịch',payment:'Tham khảo điều khoản thanh toán',guide:'Hướng dẫn sử dụng',master:'Quản lý dữ liệu gốc',loaded:'Đã tải mẫu Excel gốc.',import:'Nhập Excel',export:'Tải Excel',print:'In / Lưu PDF',choose:'Chọn dữ liệu để điền vào biểu mẫu',customer:'Khách hàng',address:'Địa chỉ khách hàng',term:'Điều khoản thanh toán',product:'Sản phẩm',hint:'Dữ liệu tham khảo được chọn trực tiếp tại trường tương ứng, không còn hiển thị thành tab riêng.',order:'Số đơn',date:'Ngày đơn hàng',transport:'Phương thức vận chuyển',destination:'Cảng đến',products:'Danh sách sản phẩm',add:'Thêm dòng',no:'STT',sku:'Mã hàng / SKU',vi:'Tên hàng (Tiếng Việt)',en:'Tên hàng (English)',zh:'Tên hàng (中文)',unit:'Đơn vị',qty:'Số lượng',price:'Đơn giá (USD)',amount:'Thành tiền (USD)',action:'Thao tác',total:'Tổng cộng',other:'5. Các điều khoản khác',notes:'6. Ghi chú',buyer:'BÊN MUA',seller:'BÊN BÁN',sign:'(Ký tên, đóng dấu)',agree:'Hai bên đã đọc, hiểu rõ và đồng ý với toàn bộ nội dung nêu trên, cùng ký xác nhận.',role:'Quyền người dùng',admin:'Quản trị viên',editor:'Nhân viên nhập liệu',viewer:'Chỉ xem',editable:'Được chỉnh sửa dữ liệu gốc',readonly:'Chỉ được xem',close:'Đóng',addNew:'Thêm mới'},
zh:{title:'成交确认书',appendix:'成交确认书附录',payment:'付款条款参考',guide:'使用说明',master:'基础数据管理',loaded:'已加载原始 Excel 模板。',import:'导入 Excel',export:'导出 Excel',print:'打印 / 保存 PDF',choose:'选择数据并填入表单',customer:'客户',address:'客户地址',term:'付款条款',product:'产品',hint:'参考数据在对应字段中直接选择，不再作为独立标签页显示。',order:'订单号',date:'订单日期',transport:'运输方式',destination:'目的港',products:'产品清单',add:'添加行',no:'序号',sku:'物料编码 / SKU',vi:'产品名称（越文）',en:'产品名称（英文）',zh:'产品名称（中文）',unit:'单位',qty:'数量',price:'单价（USD）',amount:'金额（USD）',action:'操作',total:'合计',other:'5. 其他条款',notes:'6. 备注',buyer:'买方',seller:'卖方',sign:'（签字、盖章）',agree:'双方已阅读、理解并同意上述全部内容，现签字确认。',role:'用户权限',admin:'管理员',editor:'录入员',viewer:'只读',editable:'可编辑基础数据',readonly:'仅查看',close:'关闭',addNew:'新增'},
en:{title:'Transaction Confirmation',appendix:'Transaction Confirmation Appendix',payment:'Payment Terms Reference',guide:'User Guide',master:'Master Data Management',loaded:'Original Excel template loaded.',import:'Import Excel',export:'Download Excel',print:'Print / Save PDF',choose:'Select data to fill the form',customer:'Customer',address:'Customer address',term:'Payment terms',product:'Product',hint:'Reference data is selected directly in the corresponding fields instead of being shown as separate tabs.',order:'Order No.',date:'Order date',transport:'Transport method',destination:'Destination port',products:'Product list',add:'Add row',no:'No.',sku:'Item code / SKU',vi:'Product name (Vietnamese)',en:'Product name (English)',zh:'Product name (Chinese)',unit:'Unit',qty:'Quantity',price:'Unit price (USD)',amount:'Amount (USD)',action:'Actions',total:'Total',other:'5. Other terms',notes:'6. Notes',buyer:'BUYER',seller:'SELLER',sign:'(Signature and stamp)',agree:'Both parties have read, understood and agreed to all contents above and hereby sign for confirmation.',role:'User role',admin:'Administrator',editor:'Data editor',viewer:'View only',editable:'Master data editing allowed',readonly:'View only',close:'Close',addNew:'Add new'}};
const TERMS={vi:['Nếu người nhận hàng là bên thứ ba không phải Bên Mua, Bên Mua vẫn phải thanh toán trực tiếp cho Bên Bán đầy đủ số tiền theo Bản xác nhận này.','Bản xác nhận này là một phần không thể tách rời của hợp đồng được ký giữa Bên Mua và Bên Bán. Các nội dung chưa quy định sẽ thực hiện theo hợp đồng.','Bản quét, bản sao và chữ ký điện tử có giá trị pháp lý tương đương bản gốc và chữ ký trực tiếp.','Sau khi hàng được vận chuyển tới địa điểm chỉ định, người nhận hàng tiến hành ký nhận. Chứng từ ký nhận được dùng để đối chiếu số lượng.'],zh:['若收货人为买方以外的第三方，买方仍应按本确认书约定向卖方支付全部款项。','本确认书是买卖双方合同不可分割的一部分，未约定事项按合同执行。','扫描件、复印件及电子签名与原件和手写签名具有同等法律效力。','货物运至指定地点后由指定收货人签收，签收凭证用于核对数量。'],en:['If the consignee is a third party other than the Buyer, the Buyer remains responsible for paying the Seller in full under this confirmation.','This confirmation forms an inseparable part of the contract between the Buyer and Seller. Matters not stated herein shall follow the contract.','Scanned copies, copies and electronic signatures have the same legal effect as originals and handwritten signatures.','After delivery to the designated location, the designated consignee shall acknowledge receipt. Signed receiving documents are used to verify quantity.']};
const NOTE={vi:'Bên Bán xuất hóa đơn GTGT theo mức thuế suất pháp định tại thời điểm xuất hóa đơn. Nếu thuế suất thay đổi, giá bán được điều chỉnh tương ứng.',zh:'卖方按开票时的法定税率开具增值税发票；如税率变化，销售价格相应调整。',en:'The Seller will issue a VAT invoice at the statutory tax rate effective on the invoice date. The selling price will be adjusted if the tax rate changes.'};

function rowsOf(ws){return ws?XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false}).map(r=>r.map(v=>String(v??'').trim())):[]}
const norm=s=>String(s||'').toLowerCase().replace(/\s+/g,' ').trim();
function findHeader(rows,aliases){for(let r=0;r<Math.min(rows.length,25);r++)for(let c=0;c<(rows[r]||[]).length;c++)if(aliases.some(a=>norm(rows[r][c]).includes(norm(a))))return{r,c};return null}
function records(rows,type){if(!rows.length)return[];const A=type==='customer'?{code:['客户编码','customer code'],cn:['中文名称'],vi:['越南名称'],en:['英文名称'],short:['简称'],address:['地址'],tax:['税号']}:{code:['物料编码','sku'],cn:['小类','中文名称','商品名称'],vi:['越南名称','commodities name(vn)'],en:['英文名称','commodities name(en)'],unit:['单位'],price:['单价','price']};const hits=Object.fromEntries(Object.entries(A).map(([k,v])=>[k,findHeader(rows,v)]));const hr=Math.max(0,...Object.values(hits).filter(Boolean).map(x=>x.r));return rows.slice(hr+1).map((row,i)=>{const o={_row:hr+1+i};Object.entries(hits).forEach(([k,h])=>o[k]=h?row[h.c]||'':'');return o}).filter(o=>o.code||o.vi||o.en||o.cn)}
function genericRecords(rows){return rows.filter(r=>r.some(Boolean)).slice(1).map((r,i)=>({_row:i+1,code:r[0]||'',vi:r[1]||r[0]||'',en:r[2]||r[1]||'',cn:r[3]||''})).filter(x=>x.code||x.vi||x.en||x.cn)}
function label(rec,lang){return rec?.[lang==='zh'?'cn':lang]||rec?.vi||rec?.en||rec?.cn||rec?.code||''}

function App(){
 const [wb,setWb]=useState(null),[active,setActive]=useState('confirmation'),[lang,setLang]=useState('vi'),[role,setRole]=useState('admin'),[notice,setNotice]=useState(T.vi.loaded),[masterOpen,setMasterOpen]=useState(false),[sourceSheet,setSourceSheet]=useState(CUSTOMER_SHEET);
 const [customerIndex,setCustomerIndex]=useState(''),[customer,setCustomer]=useState(''),[customerCode,setCustomerCode]=useState(''),[taxCode,setTaxCode]=useState(''),[address,setAddress]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10));
 const [items,setItems]=useState([{productIndex:'',sku:'',vi:'',en:'',cn:'',unit:'',qty:1,price:0}]); const tr=T[lang]; const canEdit=role!=='viewer';
 useEffect(()=>{fetch('/mau-xac-nhan-giao-dich.xlsx').then(r=>r.arrayBuffer()).then(b=>{const w=XLSX.read(b,{type:'array',cellStyles:true});setWb(w);setNotice(T[lang].loaded)}).catch(e=>setNotice(e.message))},[]);
 const customers=useMemo(()=>records(rowsOf(wb?.Sheets?.[CUSTOMER_SHEET]),'customer'),[wb]);
 const products=useMemo(()=>records(rowsOf(wb?.Sheets?.[PRODUCT_SHEET]),'product'),[wb]);
 const payments=useMemo(()=>{for(const s of PAYMENT_SHEETS){const x=genericRecords(rowsOf(wb?.Sheets?.[s]));if(x.length)return x}return[{code:'DAP',vi:'DAP - Giao tại nơi đến',en:'DAP - Delivered at Place',cn:'DAP - 目的地交货'}]},[wb]);
 const addresses=useMemo(()=>{for(const s of ADDRESS_SHEETS){const x=genericRecords(rowsOf(wb?.Sheets?.[s]));if(x.length)return x}return[]},[wb]);
 function importExcel(e){const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=x=>{setWb(XLSX.read(x.target.result,{type:'array',cellStyles:true}));setNotice(`${tr.import}: ${f.name}`)};rd.readAsArrayBuffer(f)}
 function selectCustomer(i){setCustomerIndex(i);const c=customers[i];if(!c){setCustomer('');setCustomerCode('');setTaxCode('');setAddress('');return}setCustomer(label(c,lang));setCustomerCode(c.code||'');setTaxCode(c.tax||'');const match=addresses.find(a=>a.code===c.code||norm(a.vi).includes(norm(c.vi))||norm(c.vi).includes(norm(a.vi)));setAddress(c.address||label(match,lang)||'')}
 function selectProduct(rowIndex,productIndex){const p=products[productIndex];if(!p)return;setItems(list=>list.map((x,n)=>n===rowIndex?{...x,productIndex:String(productIndex),sku:p.code,vi:p.vi,en:p.en,cn:p.cn,unit:p.unit||'',price:Number(p.price||0)}:x))}
 function addBlank(){setItems(v=>[...v,{productIndex:'',sku:'',vi:'',en:'',cn:'',unit:'',qty:1,price:0}])}
 function patch(i,k,v){setItems(list=>list.map((x,n)=>n===i?{...x,[k]:['qty','price'].includes(k)?Number(v):v}:x))}
 function exportExcel(){const out=XLSX.utils.book_new();XLSX.utils.book_append_sheet(out,XLSX.utils.json_to_sheet(items.map((x,i)=>({STT:i+1,SKU:x.sku,'Tên sản phẩm':x.vi,'中文名称':x.cn,'Đơn vị':x.unit,'Số lượng':x.qty,'Đơn giá':x.price,'Thành tiền':x.qty*x.price}))), 'Xác nhận giao dịch');if(wb)wb.SheetNames.forEach(s=>XLSX.utils.book_append_sheet(out,wb.Sheets[s],s.slice(0,31)));XLSX.writeFile(out,'xac-nhan-giao-dich.xlsx')}
 const total=items.reduce((s,x)=>s+x.qty*x.price,0);
 const nav=[['confirmation',tr.title,FileText],['appendix',tr.appendix,FileText],['payment',tr.payment,Database],['guide',tr.guide,BookOpen]];
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="logo">海天</div><div><b>Haday Việt Nam</b><small>{tr.title}</small></div></div><nav>{nav.map(([id,name,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}><Icon/><span>{name}</span></button>)}</nav><button className="source-button" onClick={()=>setMasterOpen(true)}><Settings2/>{tr.master}</button><div className="role"><label>{tr.role}</label><select value={role} onChange={e=>setRole(e.target.value)}><option value="admin">{tr.admin}</option><option value="editor">{tr.editor}</option><option value="viewer">{tr.viewer}</option></select><p><LockKeyhole/>{canEdit?tr.editable:tr.readonly}</p></div></aside>
 <main><header><div><h1>{nav.find(x=>x[0]===active)?.[1]}</h1><p>{notice}</p></div><div className="actions"><label className="language"><Globe2/><select value={lang} onChange={e=>setLang(e.target.value)}>{Object.entries(LANGS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="btn secondary"><Upload/>{tr.import}<input hidden type="file" accept=".xlsx,.xls" onChange={importExcel}/></label><button className="btn secondary" onClick={exportExcel}><Download/>{tr.export}</button>{['confirmation','appendix'].includes(active)&&<button className="btn primary" onClick={()=>window.print()}><Printer/>{tr.print}</button>}</div></header>
 {active==='confirmation'&&<Document {...{tr,lang,canEdit,customers,products,customerIndex,selectCustomer,customer,customerCode,taxCode,address,date,setDate,items,setItems,patch,selectProduct,addBlank,total}}/>}
 {active==='appendix'&&<Appendix tr={tr} items={items}/>} {active==='payment'&&<section className="card text-page"><h2>{tr.payment}</h2>{payments.map((x,i)=><p key={i}><b>{x.code}</b> — {label(x,lang)}</p>)}</section>} {active==='guide'&&<Guide tr={tr} lang={lang}/>}</main>
 {masterOpen&&<MasterModal {...{wb,setWb,role,sourceSheet,setSourceSheet,close:()=>setMasterOpen(false),tr}}/>}</div>
}

function Document(p){const {tr,lang,canEdit,customers,products,items,setItems,patch,total}=p;return <article className="document card document-compact"><div className="meta-grid customer-meta"><label>{tr.customer}<select disabled={!canEdit} value={p.customerIndex} onChange={e=>p.selectCustomer(e.target.value)}><option value="">— {tr.customer} —</option>{customers.map((x,i)=><option key={i} value={i}>{label(x,lang)}</option>)}</select></label><label>{tr.date}<input disabled={!canEdit} type="date" value={p.date} onChange={e=>p.setDate(e.target.value)}/></label><label>{lang==='zh'?'客户编码':lang==='en'?'Customer code':'Mã khách hàng'}<input readOnly value={p.customerCode}/></label><label>{lang==='zh'?'税号':lang==='en'?'Tax code':'Mã số thuế'}<input readOnly value={p.taxCode}/></label><label className="full-row">{tr.address}<input readOnly value={p.address}/></label></div><div className="section-head"><h3>{tr.products}</h3><button className="btn primary small no-print" disabled={!canEdit} onClick={p.addBlank}><Plus/>{tr.add}</button></div><div className="table-wrap"><table className="product-table compact-products"><thead><tr><th>{tr.no}</th><th>{tr.product}</th><th>{tr.sku}</th><th>{tr.zh}</th><th>{tr.unit}</th><th>{tr.qty}</th><th>{tr.price}</th><th>{tr.amount}</th><th className="no-print">{tr.action}</th></tr></thead><tbody>{items.map((x,i)=><tr key={i}><td>{i+1}</td><td className="product-choice"><select disabled={!canEdit} value={x.productIndex??''} onChange={e=>p.selectProduct(i,e.target.value)}><option value="">— {tr.product} —</option>{products.slice(0,5000).map((prod,n)=><option key={n} value={n}>{label(prod,lang)}</option>)}</select></td><td><input readOnly value={x.sku}/></td><td><input readOnly value={x.cn}/></td><td><input readOnly value={x.unit}/></td><td><input disabled={!canEdit} type="number" min="0" value={x.qty} onChange={e=>patch(i,'qty',e.target.value)}/></td><td><input disabled={!canEdit} type="number" min="0" step="0.01" value={x.price} onChange={e=>patch(i,'price',e.target.value)}/></td><td>{(x.qty*x.price).toFixed(2)}</td><td className="no-print"><button className="icon danger" disabled={!canEdit} onClick={()=>setItems(v=>v.filter((_,n)=>n!==i))}><Trash2/></button></td></tr>)}</tbody><tfoot><tr><td colSpan="7">{tr.total}</td><td>{total.toLocaleString(undefined,{minimumFractionDigits:2})} USD</td><td className="no-print"/></tr></tfoot></table></div><section className="terms"><h3>{tr.other}</h3>{TERMS[lang].map((x,i)=><p key={i}>({i+1}) {x}</p>)}<h3>{tr.notes}</h3><p>{NOTE[lang]}</p></section><div className="agreement">{tr.agree}</div><div className="signatures"><div><b>{tr.buyer}</b><span>{tr.sign}</span><p>____ / ____ / ______</p></div><div><b>{tr.seller}</b><span>{tr.sign}</span><p>____ / ____ / ______</p></div></div></article>}
function Appendix({tr,items}){return <section className="document card"><div className="doc-header"><h2>{tr.appendix}</h2></div><table className="product-table"><thead><tr><th>{tr.no}</th><th>{tr.sku}</th><th>{tr.vi}</th><th>{tr.zh}</th><th>{tr.qty}</th></tr></thead><tbody>{items.map((x,i)=><tr key={i}><td>{i+1}</td><td>{x.sku}</td><td>{x.vi}</td><td>{x.cn}</td><td>{x.qty}</td></tr>)}</tbody></table></section>}
function Guide({tr,lang}){const rows={vi:['Nhập file Excel gốc bằng nút “Nhập Excel”.','Chọn khách hàng, địa chỉ, điều khoản thanh toán và sản phẩm ngay tại trường tương ứng.','Nhấn “Thêm dòng” để thêm dòng trống; có thể sửa hoặc xóa từng dòng sản phẩm.','Chuyển đổi giao diện bằng lựa chọn Tiếng Việt, 中文 hoặc English.','Nhấn “In / Lưu PDF”, chọn khổ A4 và Save as PDF.','Quản trị viên và Nhân viên nhập liệu được chỉnh sửa dữ liệu gốc; người dùng Chỉ xem không được sửa.'],zh:['点击“导入 Excel”加载原始文件。','在对应字段选择客户、地址、付款条款和产品。','点击“添加行”新增空白产品行，可逐行修改或删除。','使用语言选择器切换越文、中文或英文。','点击“打印 / 保存 PDF”，选择 A4 并保存为 PDF。','管理员和录入员可以编辑基础数据，只读用户不能修改。'],en:['Use “Import Excel” to load the source workbook.','Select customer, address, payment terms and products in their corresponding fields.','Use “Add row” for a blank product row; each row can be edited or deleted.','Use the language selector to switch among Vietnamese, Chinese and English.','Use “Print / Save PDF”, choose A4 and save as PDF.','Administrators and data editors may edit master data; view-only users may not.']}[lang];return <section className="card text-page"><h2>{tr.guide}</h2><ol>{rows.map((x,i)=><li key={i}>{x}</li>)}</ol></section>}
function MasterModal({wb,setWb,role,sourceSheet,setSourceSheet,close,tr}){const rows=rowsOf(wb?.Sheets?.[sourceSheet]),editable=role!=='viewer',max=Math.min(40,Math.max(1,...rows.map(r=>r.length)));function update(r,c,v){if(!editable||!wb)return;const next={...wb,Sheets:{...wb.Sheets}};const ws={...next.Sheets[sourceSheet]};const a=XLSX.utils.encode_cell({r,c});ws[a]={...(ws[a]||{}),t:'s',v,w:v};next.Sheets[sourceSheet]=ws;setWb(next)}return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>{tr.master}</h2><p>{editable?tr.editable:tr.readonly}</p></div><button onClick={close}><X/></button></div><div className="source-tabs"><select value={sourceSheet} onChange={e=>setSourceSheet(e.target.value)}>{SOURCE_SHEETS.filter(s=>wb?.SheetNames.includes(s)).map(s=><option key={s}>{s}</option>)}</select></div><div className="modal-table"><table className="sheet"><tbody>{rows.slice(0,500).map((row,r)=><tr key={r}>{Array.from({length:max}).map((_,c)=><td key={c} contentEditable={editable} suppressContentEditableWarning onBlur={e=>update(r,c,e.currentTarget.textContent)}>{row[c]||''}</td>)}</tr>)}</tbody></table></div><div className="modal-foot"><button className="btn secondary" onClick={close}>{tr.close}</button></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
